[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache"
